/**
 * Entity Resolution dictionary: FootyStats team names → normalized slug
 * Used to match FootyStats CSV data with Odds-API event team names.
 * Add entries as needed when uploading CSVs.
 */
export const TEAM_NAME_MAP: Record<string, string> = {
  // Premier League
  "manchester city fc": "manchester-city",
  "manchester city": "manchester-city",
  "man city": "manchester-city",
  "manchester united fc": "manchester-united",
  "manchester united": "manchester-united",
  "man united": "manchester-united",
  "man utd": "manchester-united",
  "liverpool fc": "liverpool",
  "liverpool": "liverpool",
  "arsenal fc": "arsenal",
  "arsenal": "arsenal",
  "chelsea fc": "chelsea",
  "chelsea": "chelsea",
  "tottenham hotspur": "tottenham",
  "tottenham hotspur fc": "tottenham",
  "spurs": "tottenham",
  "afc bournemouth": "bournemouth",
  "bournemouth": "bournemouth",
  "aston villa fc": "aston-villa",
  "aston villa": "aston-villa",
  "brighton & hove albion fc": "brighton",
  "brighton & hove albion": "brighton",
  "brighton": "brighton",
  "brentford fc": "brentford",
  "brentford": "brentford",
  "west ham united fc": "west-ham",
  "west ham united": "west-ham",
  "west ham": "west-ham",
  "newcastle united fc": "newcastle",
  "newcastle united": "newcastle",
  "newcastle": "newcastle",
  "wolverhampton wanderers fc": "wolves",
  "wolverhampton wanderers": "wolves",
  "wolves": "wolves",
  "fulham fc": "fulham",
  "fulham": "fulham",
  "everton fc": "everton",
  "everton": "everton",
  "crystal palace fc": "crystal-palace",
  "crystal palace": "crystal-palace",
  "nottingham forest": "nottm-forest",
  "nottingham forest fc": "nottm-forest",
  "leeds united fc": "leeds-united",
  "leeds united": "leeds-united",
  "leeds": "leeds-united",
  "sunderland afc": "sunderland",
  "sunderland": "sunderland",
  "leicester city fc": "leicester",
  "leicester city": "leicester",
  "ipswich town fc": "ipswich",
  "ipswich town": "ipswich",
  "southampton fc": "southampton",
  "southampton": "southampton",
  "luton town fc": "luton",
  "luton town": "luton",
  "burnley fc": "burnley",
  "burnley": "burnley",
  "sheffield united": "sheffield-utd",
  "sheffield united fc": "sheffield-utd",

  // Serie A
  "juventus fc": "juventus",
  "juventus": "juventus",
  "ac milan": "ac-milan",
  "milan": "ac-milan",
  "inter milan": "inter-milan",
  "internazionale": "inter-milan",
  "fc internazionale milano": "inter-milan",
  "internazionale milano": "inter-milan",
  "as roma": "roma",
  "roma": "roma",
  "ssc napoli": "napoli",
  "napoli": "napoli",
  "atalanta bc": "atalanta",
  "atalanta bergamasca calcio": "atalanta",
  "atalanta": "atalanta",
  "acf fiorentina": "fiorentina",
  "fiorentina": "fiorentina",
  "ss lazio": "lazio",
  "lazio": "lazio",
  "torino fc": "torino",
  "torino": "torino",
  "udinese calcio": "udinese",
  "udinese": "udinese",
  "bologna fc": "bologna",
  "bologna fc 1909": "bologna",
  "bologna": "bologna",
  "cagliari calcio": "cagliari",
  "cagliari": "cagliari",
  "us lecce": "lecce",
  "lecce": "lecce",
  "genoa cfc": "genoa",
  "genoa": "genoa",
  "hellas verona": "verona",
  "hellas verona fc": "verona",
  "verona": "verona",
  "empoli fc": "empoli",
  "empoli": "empoli",
  "frosinone calcio": "frosinone",
  "frosinone": "frosinone",
  "parma calcio": "parma",
  "parma calcio 1913": "parma",
  "parma": "parma",
  "monza": "monza",
  "calcio como": "como",
  "como 1907": "como",
  "como": "como",
  "venezia fc": "venezia",
  "venezia": "venezia",
  "us sassuolo calcio": "sassuolo",
  "sassuolo": "sassuolo",
  "ac pisa 1909": "pisa",
  "pisa": "pisa",
  "us cremonese": "cremonese",
  "cremonese": "cremonese",

  // K-League 1
  "jeonbuk hyundai motors": "jeonbuk",
  "jeonbuk": "jeonbuk",
  "ulsan hd": "ulsan",
  "ulsan": "ulsan",
  "fc seoul": "fc-seoul",
  "daejeon citizen": "daejeon",
  "daejeon": "daejeon",
  "bucheon fc 1995": "bucheon",
  "bucheon": "bucheon",
  "fc anyang": "fc-anyang",
  "pohang steelers": "pohang",
  "pohang": "pohang",
  "gangwon fc": "gangwon",
  "gangwon": "gangwon",
};

/**
 * Normalize a team name from FootyStats to a slug.
 * Falls back to a slug-like version of the original name if not in the map.
 */
export function normalizeTeamName(rawName: string): string {
  // Remove suffixes like "FC Badge", "Badge", etc.
  const cleaned = rawName
    .replace(/\s+(fc\s+)?badge$/i, "")
    .replace(/\s+badge$/i, "")
    .trim()
    .toLowerCase();

  return TEAM_NAME_MAP[cleaned] ?? cleaned.replace(/\s+/g, "-").replace(/[^a-z0-9-]/g, "");
}
